// Real content from mohammedridwan.com
// block kinds: p (paragraph), h (subhead), q (quote), li (bullet), note (small note)
export const essays = [
  {
    title: 'How to get people to help you (Even If You Have Nothing To Offer)', date: 'Jan 2026', topic: 'People & Ideas',
    blocks: [
      { k: 'p', t: 'Yesterday, a young university student reached out to me on LinkedIn with a:' },
      { k: 'q', t: '“Hey, I am XXX. Your career looks interesting, I too want to be a founder. Can we chat?”' },
      { k: 'p', t: 'Delete.' },
      { k: 'p', t: 'Not because I’m a jerk. I reply to most young folks seeking help; a large part of my career was guided by mentors throughout.' },
      { k: 'p', t: 'But this is a poorly crafted DM; it’s a dead fish. Zero effort or intrigue. This DM would be ignored by the vast majority of people.' },
      { k: 'p', t: 'This happens to me a thousand times a year. And every time, I think about how I used to do this in high school/university when I was broke and unknown and what made my reach-outs work.' },
      { k: 'p', t: 'I am writing this so that a young person reading this can have better success in finding mentors and seeking help. Read below.' },
      { k: 'h', t: 'The core message is simple: Every relationship is a give-and-take relationship' },
      { k: 'p', t: 'No, for real.' },
      { k: 'p', t: 'EVERY relationship, including your spouse/bf/gf, your philanthropic mentor, your brother/sister, your closest friends & randoms on the internet, is transactional. Even the “altruistic” ones.' },
      { k: 'p', t: 'The only question is: *what are you giving?*' },
      { k: 'p', t: 'Here is the secret: **what you give doesn’t have to be tangible goods.**' },
      { k: 'p', t: 'Here’s where young people screw up. They think “giving” means money, connections, business opportunities, insider information. If you’re 22 and broke, you have none of that. So you think you have nothing to offer.' },
      { k: 'p', t: 'Wrong.' },
      { k: 'p', t: 'You are time & energy rich. But you are wealth/network/knowledge poor. You can always give these things:' },
      { k: 'li', t: '**Warmth:** making someone feel warm or joyful, e.g. a genuine compliment about their life/work' },
      { k: 'li', t: '**The gift of feeling respected**' },
      { k: 'li', t: '**The feeling of being charitable:** sounds odd, but many successful people would love the opportunity to help someone in other ways besides money. Many realize that teaching a man to fish has an exponential impact on the world.' },
      { k: 'li', t: '**Window into your world:** give them an insight into your world that they are dissociated from' },
      { k: 'li', t: '**The chance to talk about their passions** at length to someone who will listen' },
      { k: 'li', t: '**The feeling of being useful**' },
      { k: 'p', t: 'So next time you are sending out a DM as a young person, think “how can I make this person feel charitable with their time? How can I give them the feeling of helping someone out?”' },
      { k: 'p', t: 'Here is a tangible example from a DM I sent years back:' },
      { k: 'q', t: '“Hey XXX, it’s incredible to see people who look like me as a Muslim build out a unicorn publicly. My goal is to get to where you are and have a similar impact on the world. I’m stuck on [specific challenge]. If you have 5 mins for a quick phone call, I’d be happy to call you anytime, anyday. It would help me a lot! 🙂”' },
      { k: 'p', t: 'If you do end up getting on that call, you can 10x this relationship by sending them a follow-up and informing them how their advice made a *tangible impact on what you were doing.*' },
      { k: 'p', t: 'Good luck.' },
    ],
  },
  {
    title: 'LLM Prompting UX: The Two-Brain Mode Problem', date: 'Dec 2025', topic: 'AI & Machine Learning',
    blocks: [
      { k: 'h', t: 'Possibility Mode vs. Precision Mode' },
      { k: 'p', t: 'When you are interacting with an LLM and generating the first draft — your brain is in **possibility mode**. When you are editing? Your brain switches to **precision mode**.' },
      { k: 'p', t: 'There’s a weird dissonance when editing prompts to get the output you want. Generating the first draft feels incredible — like you saved 100 hours. But editing using prompts feels different.' },
      { k: 'p', t: 'You want to resort to old methods: point and click. For video gen, you start thinking maybe it’d be faster to just shoot it myself. Your brain forgets about the equipment, setup, location costs, scripting time — the 100s of hours needed to shoot that video.' },
      { k: 'p', t: 'Weird thing is: you feel **time compression** on initial draft, but **time expansion bias** when editing with prompts. Time compression bias also happens when you use a VR headset btw.' },
      { k: 'h', t: 'What’s Actually Happening?' },
      { k: 'p', t: 'Initial prompt = **possibility mode.** You feel like a kid with a magic wand. Your relative comparison point is the entire traditional creation process.' },
      { k: 'p', t: 'Editing = **precision mode.** Now you’re comparing prompt editing to just dragging something 2 px left. Your baseline shrinks from “entire process” to “this one tiny change”.' },
      { k: 'h', t: 'Loss of Agency makes you feel you are losing time faster' },
      { k: 'p', t: 'Power increases perceptions of available time, and perceived control over time underlies this effect. When you lose direct agency (point and click, instant feedback), time dilates.' },
      { k: 'p', t: 'Even when prompt editing takes 2 hours vs 200 hours traditionally, it FEELS longer because you’re passively waiting instead of actively doing. Add to this the fact that humans evolved to grab stuff and move it. When you can’t directly touch what you’re editing, your brain feels stuck and loss of time feels quicker.' },
      { k: 'p', t: '…it will be interesting to see how the UX of LLMs evolve. Early days. Lots more to work on.' },
    ],
  },
  {
    title: 'Discovering Product Market Fit', date: 'Dec 2025', topic: 'Startups & Product', popular: true,
    blocks: [
      { k: 'p', t: 'Pluto is now my second endeavour in the startup world and over time you start to notice patterns in what constitutes as “Product Market Fit”.' },
      { k: 'p', t: 'Surprisingly, it’s not that complex — and you can truly ‘vibe feel it’.' },
      { k: 'p', t: 'No one can quantifiably tell you that you have “PMF”. “PMF” is ever changing based on market conditions, your funding round, your competitors, macro-policies, interest rates, cash on hand & a thousand other factors. What feels like PMF today can disappear tomorrow and you will once again have to chase it… from scratch.' },
      { k: 'p', t: 'That being said, here are some indicators I have found to be useful to know when I am getting close:' },
      { k: 'h', t: '1. There is no “PMF”. There is “Product – Positioning – Segment – Market – Founder – Fit” instead.' },
      { k: 'li', t: 'Good Product + Bad Positioning = you are dead. Read Obviously Awesome by April Dunford.' },
      { k: 'li', t: 'Good Product + Bad Segment + Good Positioning = you are dead. You need to try and operate in a segment of your own in the 0 → 1 phase. This is not true if you have enough capital that it can act as a weapon. Read Zero to One, Competition is for Losers, and Category Pirates.' },
      { k: 'li', t: 'Bad Market (low TAM) + VC funding = dead. Venture Capital inherently **requires** you to have minimum 30% MoM growth in the early stages; hard to do that if your TAM is tiny.' },
      { k: 'li', t: 'Good Everything + You hate the market / can’t sell to it as founders = dead. Startups are incredibly difficult; don’t choose a game you don’t want to play.' },
      { k: 'h', t: '2. Minimum 25% MoM growth for 24+ months.' },
      { k: 'p', t: 'This is the minimum bar. Until you are here, you don’t have PMF. Trust me.' },
      { k: 'h', t: '3. High number of logos > Whales' },
      { k: 'p', t: 'This is counterintuitive; founders understandably get excited when they get large scale deals or shiny logos. Bad idea to rely on those in the early stage. If 60%+ of your revenue comes from 1-2 deals you have severe concentration risks and chances are you built a whole bunch of excess to serve these few customers.' },
      { k: 'p', t: 'Enterprise deals feel validating. Big numbers. Logo recognition. But they’re often a trap. You end up building custom features for one client’s edge case. When you have real PMF, you’re stacking small-to-mid logos. Lots of them. **Similar use cases. Repeatable sales motion.** **Until then, you may have a business, but you don’t have PMF.** You want a school of fish, all demanding similar things.' },
      { k: 'h', t: '4 – 12. The rest of the checklist' },
      { k: 'li', t: '**Positive ROAS / you found 3-4 ad creatives that actually work consistently.** You know you can put more $$$ in to get more $$$$ out — you found a good positioning.' },
      { k: 'li', t: '**For the marketing folks:** you can create lead magnets your customers actually give a shit about.' },
      { k: 'li', t: '**Customers are annoyed if you have downtime or issues.**' },
      { k: 'li', t: '**Queries coming in from customers are actually in-depth product usage questions.**' },
      { k: 'li', t: '**You can charge a lot of customers some meaningful amount / you can convert from free to paid without climbing a hill.**' },
      { k: 'li', t: 'There is a clear path to make the customer more valuable with time, i.e. upsells.' },
      { k: 'li', t: 'Your customers are impatient and want you to resolve their issues without threatening to leave.' },
      { k: 'li', t: '**Low activation time post-sales:** if your sales team signs contracts and customers aren’t chasing you to activate — you don’t have PMF. Also, if you send invoices and a large chunk of customers don’t pay for months even with the threat of discontinuing your service — you don’t have PMF.' },
      { k: 'li', t: 'If you were in a problem-unaware segment and you start to see shifts to problem-aware in sales calls without you teaching them — and it happens often — you are getting close.' },
      { k: 'p', t: 'As a rule of thumb, your PMF variables change after **every raise** at the bare minimum. New raise, new goals, new search for PMF unless it’s a Series A (where you will most likely be doing more of the same but with greater firepower).' },
      { k: 'p', t: 'Good luck!' },
    ],
  },
  {
    title: 'Running Product Teams at Early Stage Startups – Xpand Conf 2024', date: 'Sep 2024', topic: 'Startups & Product',
    blocks: [
      { k: 'yt', id: 'ggjpoteeqVw' },
    ],
  },
  {
    title: 'Customer engagement is a better indicator of retention than customer satisfaction', date: 'Sep 2024', topic: 'Startups & Product',
    blocks: [
      { k: 'p', t: 'Recently, I was hiring for an account management role, and during one of the interviews, the candidate shared something that stuck with me. He said that when it comes to retention, **customer engagement** is actually a better indication of loyalty than customer satisfaction.' },
      { k: 'p', t: 'At first, this idea felt counterintuitive. You’d think that as long as your customers are satisfied, they’ll stick around. But that’s not always the case. An engaged customer, even if they’re not 100% satisfied, is far less likely to churn. They’re involved, they’re connected, they have a relationship, and they’re in the habit of using your product. Meanwhile, a satisfied but unengaged customer is vulnerable. They may leave if someone else offers them a slightly better deal or a bit more satisfaction as they are purely judging you based on the offer you have for them.' },
      { k: 'p', t: 'This made me realize how important it is to focus not just on keeping customers happy but also on keeping them engaged. Engagement drives loyalty. And it’s those regular touchpoints — whether through product updates, personal outreach, or ongoing support — that keep customers connected to your brand.' },
      { k: 'p', t: 'It’s a reminder that in business, and maybe in life too, sometimes engagement matters more than satisfaction.' },
    ],
  },
  {
    title: 'AI in the workspace', date: 'Sep 2024', topic: 'AI & Machine Learning',
    blocks: [
      { k: 'img', src: 'https://mohammedridwanulf581149f2c.wordpress.com/wp-content/uploads/2024/09/image-3.png?w=1024' },
      { k: 'note', t: 'Image credits: the great designers at Perplexity' },
      { k: 'p', t: 'It’s Monday, September 9th, 2024, and I’ve noticed something strange about how I work now. I use Eraser.io AI sequence diagrams, ChatGPT, Perplexity, and Cursor every day for more than 3 hours. It feels like my whole way of working changed almost overnight, and I can’t really remember how I worked 1.5 years ago.' },
      { k: 'p', t: 'Was I really starting from scratch for every PRD, every bit of market research, or every blog post I wrote? That seems weird now. The idea of doing all that without AI feels strange. Today, it feels kind of odd that anyone would start from scratch.' },
      { k: 'p', t: 'My calories are now tracked in ChatGPT. Holiday planning? GPT. Shell script? WordPress script? GPT. AppScript to automate how I work with Google Sheets? GPT. Forgot how to easily do pivot tables — GPT? Birthday card for a friend? GPT!' },
      { k: 'p', t: 'The fact that I can’t remember what it felt like to do everything manually probably means we’re getting used to this new way of working.' },
      { k: 'p', t: 'Weird…' },
      { k: 'p', t: 'Let’s look back at this on Sep 9th, 2025.' },
    ],
  },
  {
    title: 'Price < Willingness to Pay creates suspicion & low trust when selling B2B products', date: 'Sep 2022', topic: 'Startups & Product',
    blocks: [
      { k: 'p', t: 'When the price of a product is lower than the amount the customer is willing to pay for the perceived value, the customer typically sees it as a discount and transacts with you. However, in B2B use cases, if the price of the product is less than what the customer perceives as the value or is willing to pay, it can have the counter-effect of confusing the customer about the actual value proposition.' },
      { k: 'p', t: 'This confusion often arises because many B2B products are complex, and the full range of value propositions isn’t immediately experienced by the buyer. In many cases, the buyer has to take your word for it (e.g., “we can maintain a 99.999% SLA” or “we will provide priority support”).' },
      { k: 'p', t: 'The combination of a complex product, the buyer’s inability to immediately experience all of the value propositions, and a price that’s lower than what they expect to pay can raise doubts about whether the salesperson is being truthful about the merit of the product.' },
      { k: 'p', t: 'This is something I learned during the early days of Shopify Plus, where the price was significantly lower than competitors offering large e-commerce contracts to enterprises.' },
      { k: 'p', t: 'This confusion can be avoided if the lower price is framed as a temporary discount or offer, or if it’s clearly explained what technological advantages allow you to provide such great value at that price point.' },
    ],
  },
  {
    title: 'Open sourcing Atlas – tools for Applied Deep Learning Development', date: 'Dec 2019', topic: 'AI & Machine Learning',
    blocks: [
      { k: 'p', t: 'Excited to share that my team just recently open sourced Atlas.' },
      { k: 'p', t: 'Atlas is a flexible Machine Learning platform that consists of a Python SDK, CLI, GUI & Scheduler to help Machine Learning Engineering teams dramatically reduce the model development time & reduce effort in managing infrastructure.' },
      { k: 'p', t: 'We are currently in BETA and would love the community’s help to ship a flexible, easy to use ML Platform.' },
      { k: 'p', t: '**Check out and contribute to Atlas in our GitHub repo: github.com/dessa-oss/atlas**' },
    ],
  },
  {
    title: 'Datacouncil NYC 19′ Talk', date: 'Nov 2019', topic: 'AI & Machine Learning',
    blocks: [
      { k: 'note', t: 'Oct 21 2020 update: Chip Huyen has a great thread that talks a lot about this as well — twitter.com/chipro' },
      { k: 'p', t: 'Building Systems to Monitor Data and Model Health in Production Systems.' },
      { k: 'p', t: 'Unlike traditional deterministic software, models in production start to degrade as soon as they have been deployed. Typically these degradations are caused by three broad types of problems:' },
      { k: 'li', t: '**Bugs in the data pipeline:** this can manifest in many different ways, e.g. someone changes code upstream and now a particular column could be filled with NaNs.' },
      { k: 'li', t: '**Input distribution shifts:** caused by changes in real-world phenomena, e.g. a bank has a churn prediction model — their competitor has just released a new competitive campaign. This can manifest in distribution shifts as customer behavior changes.' },
      { k: 'li', t: '**Concept drift:** this happens when the actual relationship between the input and output changes.' },
      { k: 'p', t: 'Traditional testing infrastructure is currently not suitable to handle the dynamic nature of machine learning.' },
      { k: 'yt', id: 'WZNEsc7ynxI' },
      { k: 'p', t: 'In this talk, Mohammed Ridwanul, Product Manager at Dessa, speaks about writing tests to monitor machine learning models, creating data contracts and metadata stores for reference checks and building automated systems around model testing to prevent degradation in production.' },
    ],
  },
  {
    title: 'Startup in the spotlight: SnapTravel w/ Henry Shi (CTO)', date: 'Nov 2019', topic: 'Startups & Product',
    blocks: [
      { k: 'p', t: 'I recently got to interview Henry Shi (CTO & Co-Founder at SnapTravel). SnapTravel is a company that I am extremely bullish on; it remains to be seen what they do next, but talking to Henry makes me even more confident of their trajectory.' },
      { k: 'yt', id: 'nmeShriKPWU' },
      { k: 'note', t: 'In this Terminal Tech Talk we bring you Henry Shi, co-founder and CTO of SnapTravel, in conversation with Mohammed Ridwanul, Product Manager at Dessa, where Mohammed’s team has built an AI platform that helps the world’s largest and most complex organizations build real-world value with advanced AI.' },
    ],
  },
  {
    title: 'The 4 dissonance effects of Virtual Reality (VR)', date: 'Sep 2019', topic: 'VR',
    blocks: [
      { k: 'note', t: 'Edit, 2024: a lot has changed since I published this post — very recently the Apple Vision Pro came to market. While it wasn’t a smash hit, it is exponentially better than any products made when this post was first published.' },
      { k: 'p', t: 'When designing products for VR, it seems that you need to consider 4 major dissonance effects. These dissonance effects can be used to create moats for products and can help you think through newer experiences. I am particularly excited about the future of VR — it looks like a toy now & is primarily used for gaming, but I believe the VR of the future will look and feel dramatically different from what we see today.' },
      { k: 'li', t: '**Focusing Effect:** when you put a VR headset on, you are ultra focused. Nothing in your real physical world matters anymore. Distractions are dramatically less likely than a user being on a computer / their phone. The friction to remove the headset & move away from the dark environment to do a different task is too high, so most of the time users are ultra focused for longer periods.' },
      { k: 'li', t: '**Time Compression:** research shows that users in general think they have spent 50% less time than they actually did when they wear a headset. So a person could be playing for an hour but think they have only spent 30 minutes. What if productive work was done in VR? Would it make us feel more tired than we expected after the tasks? Or does time compression also have the effect of energy preservation?' },
      { k: 'li', t: '**Higher ranges of motion:** a research paper showed that people with knee pain were able to jump higher when wearing a VR headset than without. The primary reason is that the dissonance with reality helps reduce pain symptoms.' },
      { k: 'li', t: '**Empathy generator:** wearing a VR headset gives you an immersive POV; by seeing the world in the immersive POV of a different individual, you are more likely to generate empathy for others.' },
      { k: 'q', t: 'The next big thing will start out looking like a toy. — Chris Dixon' },
    ],
  },
];
